services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ffmpeg", "-version"]
      interval: 60s
      timeout: 5s
      retries: 3
